import { normalizeRoutePath } from "./url";
import type { KnowledgeDocumentGroup } from "./knowledge-documents";

export interface SupplementalKnowledgePage {
  slug: string;
  path: string;
  title: string;
  group: KnowledgeDocumentGroup;
}

const basePath = "/บริการและข้อมูลสำคัญ";

const supplementalKnowledgeGroups: Array<{ slug: string; group: KnowledgeDocumentGroup }> = [
  {
    slug: "ethics-code",
    group: {
      title: "ประมวลจริยะธรรม",
      open: true,
      documents: [
        {
          title: "o15 การลงนามปฏิญญาคุณธรรม",
          description: "เอกสารเผยแพร่รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-01-o15-การลงนามปฏิญญาคุณธรรม.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-01-o15-การลงนามปฏิญญาคุณธรรม.pdf",
          hasUsableTarget: true,
        },
        {
          title: "o15 กิจกรรมอบรมสอดแทรกสาระด้านจริยธรรมฯ",
          description: "เอกสารเผยแพร่รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-02-o15-กิจกรรมอบรมสอดแทรกสาระด้านจริยธรรมฯ.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-02-o15-กิจกรรมอบรมสอดแทรกสาระด้านจริยธรรมฯ.pdf",
          hasUsableTarget: true,
        },
        {
          title: "o15 ข้อบังคับ คกก สทร ว่าด้วยประมวลจริยธรรมในการปฏิบัติงาน 2565",
          description: "เอกสารเผยแพร่รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-03-o15-ข้อบังคับ-คกก-สทร-ว่าด้วยประมวลจริยธรรมในการปฏิบัติงาน-2565.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-03-o15-ข้อบังคับ-คกก-สทร-ว่าด้วยประมวลจริยธรรมในการปฏิบัติงาน-2565.pdf",
          hasUsableTarget: true,
        },
        {
          title: "o15 คำสั่งแต่งตั้งคณะทำงานขับเคลื่อนจริยธรรม 2569",
          description: "เอกสารเผยแพร่รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-04-o15-คำสั่งแต่งตั้งคณะทำงานขับเคลื่อนจริยธรรม-2569.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-04-o15-คำสั่งแต่งตั้งคณะทำงานขับเคลื่อนจริยธรรม-2569.pdf",
          hasUsableTarget: true,
        },
        {
          title: "o15 สื่อ DO and Dont RTRDA",
          description: "เอกสารเผยแพร่รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-05-o15-สื่อ-DO-and-Dont-RTRDA.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-05-o15-สื่อ-DO-and-Dont-RTRDA.pdf",
          hasUsableTarget: true,
        },
        {
          title: "o15_ข้อกำหนดว่าด้วยกระบวนการรักษาจริยธรรม",
          description: "เอกสารเผยแพร่รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-06-o15_ข้อกำหนดว่าด้วยกระบวนการรักษาจริยธรรม.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-06-o15_ข้อกำหนดว่าด้วยกระบวนการรักษาจริยธรรม.pdf",
          hasUsableTarget: true,
        },
        {
          title: "o15_ประมวลจริยธรรม",
          description: "เอกสารเผยแพร่รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-07-o15_ประมวลจริยธรรม.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/ethics-code-07-o15_ประมวลจริยธรรม.pdf",
          hasUsableTarget: true,
        },
      ],
    },
  },
  {
    slug: "complaint-practice",
    group: {
      title: "แนวปฏิบัติการจัดการเรื่องร้องเรียนการทุจริตและประพฤติมิชอบ",
      open: true,
      documents: [
        {
          title: "o 16 แนวทางปฏิบัติ การจัดการเรื่องร้องเรียน",
          description: "เอกสารเผยแพร่รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/complaint-practice-01-o-16-แนวทางปฏิบัติ-การจัดการเรื่องร้องเรียน.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/complaint-practice-01-o-16-แนวทางปฏิบัติ-การจัดการเรื่องร้องเรียน.pdf",
          hasUsableTarget: true,
        },
      ],
    },
  },
  {
    slug: "complaint-statistics",
    group: {
      title: "ข้อมูลสถิติเรื่องร้องเรียนการทุจริตและประพฤติมิชอบ",
      open: true,
      documents: [
        {
          title: "รายงานข้อมูลสถิติเรื่องร้องเรียนการทุจร",
          description: "เอกสารเผยแพร่รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/complaint-statistics-01-รายงานข้อมูลสถิติเรื่องร้องเรียนการทุจร.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/complaint-statistics-01-รายงานข้อมูลสถิติเรื่องร้องเรียนการทุจร.pdf",
          hasUsableTarget: true,
        },
      ],
    },
  },
  {
    slug: "participation-results",
    group: {
      title: "ผลการเปิดโอกาสให้มีส่วนร่วมในการดำเนินงาน",
      open: true,
      documents: [
        {
          title: "เอกสารประกอบที่ 1 คำสั่งสทรที่52-2568",
          description: "เอกสารประกอบและรายงานผลการมีส่วนร่วมรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-01-เอกสารประกอบที่-1-คำสั่งสทรที่52-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-01-เอกสารประกอบที่-1-คำสั่งสทรที่52-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "เอกสารประกอบที่ 2 รายงานประชุม ครั้งที่ 4-2568",
          description: "เอกสารประกอบและรายงานผลการมีส่วนร่วมรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-02-เอกสารประกอบที่-2-รายงานประชุม-ครั้งที่-4-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-02-เอกสารประกอบที่-2-รายงานประชุม-ครั้งที่-4-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "เอกสารประกอบที่ 3 สรุปการประชุมTechnical Hearing",
          description: "เอกสารประกอบและรายงานผลการมีส่วนร่วมรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-03-เอกสารประกอบที่-3-สรุปการประชุมTechnical-Hearing.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-03-เอกสารประกอบที่-3-สรุปการประชุมTechnical-Hearing.pdf",
          hasUsableTarget: true,
        },
        {
          title: "เอกสารประกอบที่ 4 รายงานประชุม ครั้งที่ 10-2568",
          description: "เอกสารประกอบและรายงานผลการมีส่วนร่วมรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-04-เอกสารประกอบที่-4-รายงานประชุม-ครั้งที่-10-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-04-เอกสารประกอบที่-4-รายงานประชุม-ครั้งที่-10-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "เอกสารประกอบที่ 5 รายงานการประชุม ครั้งที่ 26(4)-2568",
          description: "เอกสารประกอบและรายงานผลการมีส่วนร่วมรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-05-เอกสารประกอบที่-5-รายงานการประชุม-ครั้งที่-26-4-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-05-เอกสารประกอบที่-5-รายงานการประชุม-ครั้งที่-26-4-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "เอกสารประกอบที่ 6 รายงานการจัดทำประชาพิจารณ์",
          description: "เอกสารประกอบและรายงานผลการมีส่วนร่วมรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-06-เอกสารประกอบที่-6-รายงานการจัดทำประชาพิจารณ์.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-06-เอกสารประกอบที่-6-รายงานการจัดทำประชาพิจารณ์.pdf",
          hasUsableTarget: true,
        },
        {
          title: "แบบฟอร์มการมีส่วนร่วมo19_v3",
          description: "เอกสารประกอบและรายงานผลการมีส่วนร่วมรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-07-แบบฟอร์มการมีส่วนร่วมo19_v3.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-07-แบบฟอร์มการมีส่วนร่วมo19_v3.pdf",
          hasUsableTarget: true,
        },
        {
          title: "รายงานผลการเปิดโอกาสให้บุคคลภายนอกได้มีส่วนร่วม",
          description: "เอกสารประกอบและรายงานผลการมีส่วนร่วมรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-08-รายงานผลการเปิดโอกาสให้บุคคลภายนอกได้มีส่วนร่วม.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/participation-results-08-รายงานผลการเปิดโอกาสให้บุคคลภายนอกได้มีส่วนร่วม.pdf",
          hasUsableTarget: true,
        },
      ],
    },
  },
  {
    slug: "no-gift-policy",
    group: {
      title: "การขับเคลื่อนนโยบาย NO GIFT POLICY จากการปฏิบัติหน้าที่และการเสริมสร้างความรู้เกี่ยวกับหลักเกณฑ์การรับทรัพย์สินหรือประโยชน์อื่นใดโดยธรรมจรรยาของเจ้าพนักงานของรัฐ",
      open: true,
      documents: [
        {
          title: "o20หนังสือประกาศเจตนารมณ์ No Gift Policy ฉบับภาษาไทย",
          description: "เอกสารประกอบนโยบาย No Gift Policy รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/no-gift-policy-01-o20หนังสือประกาศเจตนารมณ์-No-Gift-Policy-ฉบับภาษาไทย.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/no-gift-policy-01-o20หนังสือประกาศเจตนารมณ์-No-Gift-Policy-ฉบับภาษาไทย.pdf",
          hasUsableTarget: true,
        },
        {
          title: "รายงานผลการดำเนินงานตามนโยบาย No Gift Policy 2568",
          description: "เอกสารประกอบนโยบาย No Gift Policy รูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/no-gift-policy-02-รายงานผลการดำเนินงานตามนโยบาย-No-Gift-Policy-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/no-gift-policy-02-รายงานผลการดำเนินงานตามนโยบาย-No-Gift-Policy-2568.pdf",
          hasUsableTarget: true,
        },
      ],
    },
  },
  {
    slug: "procurement-summary",
    group: {
      title: "สรุปจัดซื้อจัดจ้าง",
      open: true,
      documents: [
        {
          title: "O11 ไตรมาสที่ 1",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-01-O11-ไตรมาสที่-1.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-01-O11-ไตรมาสที่-1.pdf",
          hasUsableTarget: true,
        },
        {
          title: "O11 ไตรมาสที่ 2",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-02-O11-ไตรมาสที่-2.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-02-O11-ไตรมาสที่-2.pdf",
          hasUsableTarget: true,
        },
        {
          title: "1.สขร.เดือน ตุลาคม 2567",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-03-1.สขร.เดือน-ตุลาคม-2567.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-03-1.สขร.เดือน-ตุลาคม-2567.pdf",
          hasUsableTarget: true,
        },
        {
          title: "10.สขร เดือน กรกฎาคม 2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-04-10.สขร-เดือน-กรกฎาคม-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-04-10.สขร-เดือน-กรกฎาคม-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "11.สขร เดือน สิงหาคม 2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-05-11.สขร-เดือน-สิงหาคม-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-05-11.สขร-เดือน-สิงหาคม-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "12.สขร.เดือน กันยายน 2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-06-12.สขร.เดือน-กันยายน-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-06-12.สขร.เดือน-กันยายน-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "2..สขร.เดือน พฤศจิกายน 2567",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-07-2..สขร.เดือน-พฤศจิกายน-2567.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-07-2..สขร.เดือน-พฤศจิกายน-2567.pdf",
          hasUsableTarget: true,
        },
        {
          title: "3.สขร. เดือน ธันวาคม2567",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-08-3.สขร.-เดือน-ธันวาคม2567.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-08-3.สขร.-เดือน-ธันวาคม2567.pdf",
          hasUsableTarget: true,
        },
        {
          title: "4.สขร.เดือน มกราคม 2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-09-4.สขร.เดือน-มกราคม-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-09-4.สขร.เดือน-มกราคม-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "5.สขร.เดือน กุมภาพันธ์ 2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-10-5.สขร.เดือน-กุมภาพันธ์-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-10-5.สขร.เดือน-กุมภาพันธ์-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "6.สขร เดือน มีนาคม 2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-11-6.สขร-เดือน-มีนาคม-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-11-6.สขร-เดือน-มีนาคม-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "7.สขร เดือน เมษายน 2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-12-7.สขร-เดือน-เมษายน-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-12-7.สขร-เดือน-เมษายน-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "8.สขร เดือน พฤษภาคม 2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-13-8.สขร-เดือน-พฤษภาคม-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-13-8.สขร-เดือน-พฤษภาคม-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "9.สขร เดือน มิถุนายน 2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-14-9.สขร-เดือน-มิถุนายน-2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-14-9.สขร-เดือน-มิถุนายน-2568.pdf",
          hasUsableTarget: true,
        },
        {
          title: "แบบสรุปผลการจัดซื้อจัดจ้าง ประจำปีงบประมาณ พ.ศ.2568",
          description: "เอกสารสรุปข้อมูลจัดซื้อจัดจ้างรูปแบบ PDF",
          coverImage: null,
          coverAlt: "",
          previewHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-15-แบบสรุปผลการจัดซื้อจัดจ้าง-ประจำปีงบประมาณ-พ.ศ.2568.pdf",
          downloadHref: "/wp-content/uploads/knowledge-ethics-2569/procurement-summary-15-แบบสรุปผลการจัดซื้อจัดจ้าง-ประจำปีงบประมาณ-พ.ศ.2568.pdf",
          hasUsableTarget: true,
        },
      ],
    },
  },
];

export const supplementalKnowledgePages: SupplementalKnowledgePage[] = supplementalKnowledgeGroups.map(
  ({ slug, group }) => ({
    slug,
    path: `${basePath}/${slug}`,
    title: group.title,
    group,
  }),
);

export function getSupplementalKnowledgePage(path: string): SupplementalKnowledgePage | null {
  const normalized = normalizeRoutePath(path).normalize("NFC");
  return supplementalKnowledgePages.find((page) => page.path === normalized) ?? null;
}
