import type {
  WpContentRecord,
  WpDownloadAsset,
  WpNavigationItem,
} from "@/lib/wp/types";

export const MOCK_RECORDS: WpContentRecord[] = [
  {
    id: "1",
    wpId: 1,
    language: "th",
    kind: "page",
    path: "/",
    sourceUrl: "https://www.rtrda.or.th/",
    title: "สถาบันวิจัยและพัฒนาเทคโนโลยีระบบราง",
    excerpt: "หน่วยงานวิจัยและพัฒนาเทคโนโลยีระบบราง เพื่อยกระดับระบบรางไทยอย่างยั่งยืน",
    contentHtml: "<p>ยินดีต้อนรับสู่เว็บไซต์ สทร. (ข้อมูลตัวอย่างสำหรับการพัฒนา)</p>",
    modified: "2025-01-01T00:00:00",
    date: "2025-01-01T00:00:00",
    parentPath: null,
    categoryIds: [],
    featuredMediaId: null,
    featuredMediaPath: "/stitch-assets/home-hero.png",
  },
  {
    id: "2",
    wpId: 2,
    language: "en",
    kind: "page",
    path: "/en",
    sourceUrl: "https://www.rtrda.or.th/en",
    title: "Rail Technology Research and Development Agency",
    excerpt: "Research and development for Thailand rail technology and sustainable rail systems.",
    contentHtml: "<p>Welcome to RTRDA (mock data for development).</p>",
    modified: "2025-01-01T00:00:00",
    date: "2025-01-01T00:00:00",
    parentPath: null,
    categoryIds: [],
    featuredMediaId: null,
    featuredMediaPath: "/stitch-assets/home-hero.png",
  },
  {
    id: "3",
    wpId: 3,
    language: "th",
    kind: "page",
    path: "/เกี่ยวกับ-สทร",
    sourceUrl: "https://www.rtrda.or.th/เกี่ยวกับ-สทร",
    title: "เกี่ยวกับ สทร.",
    excerpt: "ประวัติและพันธกิจของสถาบันวิจัยและพัฒนาเทคโนโลยีระบบราง",
    contentHtml: "<p>สถาบันวิจัยและพัฒนาเทคโนโลยีระบบราง (สทร.) จัดตั้งขึ้นตามพระราชกฤษฎีกา</p>",
    modified: "2025-01-01T00:00:00",
    date: "2025-01-01T00:00:00",
    parentPath: null,
    categoryIds: [],
    featuredMediaId: null,
    featuredMediaPath: "/stitch-assets/rail-lab.png",
  },
  {
    id: "4",
    wpId: 4,
    language: "th",
    kind: "post",
    path: "/ข่าวสาร-กิจกรรม/ข่าวตัวอย่าง",
    sourceUrl: "https://www.rtrda.or.th/ข่าวสาร-กิจกรรม/ข่าวตัวอย่าง",
    title: "ข่าวตัวอย่างสำหรับการพัฒนา",
    excerpt: "นี่คือตัวอย่างข่าวสารที่ใช้ในการพัฒนาระบบ",
    contentHtml: "<p>เนื้อหาข่าวตัวอย่าง สำหรับทดสอบการแสดงผล</p>",
    modified: "2025-06-01T00:00:00",
    date: "2025-06-01T00:00:00",
    parentPath: "/ข่าวสาร-กิจกรรม",
    categoryIds: [],
    featuredMediaId: null,
    featuredMediaPath: "/stitch-assets/rail-network.png",
  },
  {
    id: "5",
    wpId: 5,
    language: "th",
    kind: "post",
    path: "/ข่าวสาร-กิจกรรม/ข่าวตัวอย่าง-2",
    sourceUrl: "https://www.rtrda.or.th/ข่าวสาร-กิจกรรม/ข่าวตัวอย่าง-2",
    title: "ข่าวล่าสุด: ความก้าวหน้าระบบราง",
    excerpt: "อัพเดทความก้าวหน้าการพัฒนาระบบรางของประเทศไทย",
    contentHtml: "<p>เนื้อหาข่าวล่าสุด</p>",
    modified: "2025-06-10T00:00:00",
    date: "2025-06-10T00:00:00",
    parentPath: "/ข่าวสาร-กิจกรรม",
    categoryIds: [],
    featuredMediaId: null,
    featuredMediaPath: "/stitch-assets/rail-strategy-map.png",
  },
];

export const MOCK_NAV: WpNavigationItem[] = [
  { label: "หน้าแรก", href: "/", path: "/", external: false, children: [] },
  { label: "เกี่ยวกับ สทร.", href: "/เกี่ยวกับ-สทร", path: "/เกี่ยวกับ-สทร", external: false, children: [] },
  { label: "ข่าวสาร/กิจกรรม", href: "/ข่าวสาร-กิจกรรม", path: "/ข่าวสาร-กิจกรรม", external: false, children: [] },
  { label: "ติดต่อเรา", href: "/ติดต่อเรา", path: "/ติดต่อเรา", external: false, children: [] },
];

export const MOCK_NAV_EN: WpNavigationItem[] = [
  { label: "Home", href: "/en", path: "/en", external: false, children: [] },
  { label: "About RTRDA", href: "/en/เกี่ยวกับ-สทร", path: "/en/เกี่ยวกับ-สทร", external: false, children: [] },
  { label: "Contact Us", href: "/en/ติดต่อเรา", path: "/en/ติดต่อเรา", external: false, children: [] },
];

export const MOCK_DOWNLOADS: WpDownloadAsset[] = [
  {
    id: "mock-download-1",
    sourceUrl: "",
    localPath: "/sdc-downloads/sample.pdf",
    fileName: "sample.pdf",
    mimeType: "application/pdf",
    sizeBytes: 102400,
    title: "เอกสารตัวอย่าง",
    group: "general",
    sourcePages: [],
  },
];
